robot_cfg:
    kinematics:
        usd_path: "arctos_defs/arctos.usd"
        usd_robot_root: "/robot"
        isaac_usd_path: ""
        usd_flip_joints: {}
        usd_flip_joint_limits: []

        urdf_path: "arctos_defs/arctos.urdf"
        asset_root_path: "arctos_defs"

        base_link: "arctos_base"
        ee_link: "gripper_assembly_outer"
        link_names: null
        lock_joints: null
        extra_links: null

        collision_link_names: ["arctos_base", "arctos_upper", "wrist", "gripper_assembly_inner", "gripper_assembly_outer", "left_jaw", "right_jaw"]
        collision_spheres:
            arctos_base:
                - "center": [-0.15, 0.002, 0.059]
                  "radius": 0.10825
                - "center": [-0.025, 0.002, 0.041]
                  "radius": 0.10825
                - "center": [0.047, 0.0, 0.042]
                  "radius": 0.1068
            arctos_upper:
                - "center": [0.086, -0.011, -0.001]
                  "radius": 0.10856
                - "center": [0.013, 0.005, -0.001]
                  "radius": 0.10755
            wrist:
                - "center": [0.001, 0.005, -0.057]
                  "radius": 0.10663
                - "center": [-0.013, 0.01, -0.06]
                  "radius": 0.10663
                - "center": [-0.001, -0.003, -0.119]
                  "radius": 0.10663
            gripper_assembly_inner:
                - "center": [0.002, 0.002, -0.001]
                  "radius": 0.10627
            gripper_assembly_outer:
                - "center": [0.009, 0.002, -0.009]
                  "radius": 0.04935
            left_jaw:
                - "center": [0.008, 0.004, -0.008]
                  "radius": 0.01095
                - "center": [0.007, 0.011, -0.009]
                  "radius": 0.01095
                - "center": [0.008, 0.017, -0.009]
                  "radius": 0.00996
            right_jaw:
                - "center": [0.006, 0.014, -0.008]
                  "radius": 0.00985
                - "center": [0.007, 0.007, -0.009]
                  "radius": 0.00985
                - "center": [0.016, 0.016, -0.009]
                  "radius": 0.00791

        collision_sphere_buffer: 0.005
        extra_collision_spheres: {}
        self_collision_ignore:
            arctos_base: ["arctos_lower"]
            arctos_lower: ["arctos_middle"]
            arctos_middle: ["arctos_upper"]
            arctos_upper: ["wrist"]
            wrist: ["gripper_assembly_inner"]
            gripper_assembly_inner: ["gripper_assembly_outer"]
            gripper_assembly_outer: ["left_jaw", "right_jaw"]
            left_jaw: ["right_jaw"]
        self_collision_buffer: null

        use_global_cumul: True
        mesh_link_names: null

        cspace:
            joint_names: ['lower_base', 'middle_lower', 'upper_middle', 'wrist_upper', 'inner_wrist', 'outer_inner', 'slide_left', 'slide_right']
            retract_config: [0.1553, -0.0454, 0.1518, 1.2497, 0.569, 1.7226, 0.0, 0.0]
            null_space_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
            cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
            max_jerk: 10000.0
            max_acceleration: 10.0