robot_cfg:
  kinematics:
    usd_path: "arctos_defs/arctos.usd"
    usd_robot_root: "/arctos"
    isaac_usd_path: ""
    usd_flip_joints: {}
    usd_flip_joint_limits: []

    urdf_path: "arctos_defs/arctos.urdf"
    asset_root_path: "arctos_defs"

    base_link: "arctos_base"
    ee_link: "gripper_assembly_outer"
    link_names: null
    lock_joints: null
    extra_links: null

    # extra_links:
    #   attached_object:
    #     parent_link_name: "gripper_assembly_outer"
    #     link_name: "attached_object"
    #     fixed_transform: [0, 0, 0, 1, 0, 0, 0]
    #     joint_type: "FIXED"
    #     joint_name: "attach_joint"

    collision_link_names:
      - "arctos_base"
      - "arctos_upper"
      - "wrist"
      - "gripper_assembly_inner"
      - "gripper_assembly_outer"
      - "left_jaw"
      - "right_jaw"

    collision_spheres:
      arctos_base:
        - center: [-0.086, -0.003, 0.068]
          radius: 0.00127
        - center: [0.017, -0.004, 0.065]
          radius: 0.001248
      arctos_lower:
        - center: [0.008, -0.013, -0.062]
          radius: 0.001053
        - center: [0.014, 0.041, -0.108]
          radius: 0.000926
        - center: [0.02, -0.047, -0.152]
          radius: 0.000813
        - center: [-0.008, 0.028, -0.049]
          radius: 0.000954
        - center: [0.021, 0.044, -0.158]
          radius: 0.000798
      arctos_middle:
        - center: [-0.003, -0.051, 0.001]
          radius: 0.001053
        - center: [-0.011, -0.176, -0.03]
          radius: 0.001036
        - center: [-0.011, -0.182, 0.027]
          radius: 0.001027
        - center: [-0.002, -0.006, -0.002]
          radius: 0.001044
        - center: [-0.002, -0.253, -0.035]
          radius: 0.000888
        - center: [-0.008, -0.119, -0.025]
          radius: 0.001044
        - center: [-0.005, -0.228, 0.045]
          radius: 0.000931
      arctos_upper:
        - center: [0.042, -0.012, -0.005]
          radius: 0.000834
        - center: [0.087, -0.019, -0.007]
          radius: 0.000804
        - center: [0.002, -0.001, -0.004]
          radius: 0.000779
      wrist:
        - center: [0.026, 0.002, -0.035]
          radius: 0.000766
        - center: [-0.035, 0.002, -0.073]
          radius: 0.000736
        - center: [0.035, 0.002, -0.123]
          radius: 0.000695
        - center: [-0.031, 0.002, -0.123]
          radius: 0.000695
        - center: [-0.029, 0.001, -0.032]
          radius: 0.000736
      gripper_assembly_inner:
        - center: [0.005, -0.0, -0.007]
          radius: 0.000497
        - center: [0.003, -0.0, 0.011]
          radius: 0.000481
      gripper_assembly_outer:
        - center: [-0.003, -0.013, -0.02]
          radius: 0.000392
        - center: [-0.005, 0.015, -0.019]
          radius: 0.000392
        - center: [0.011, 0.009, -0.016]
          radius: 0.000355
        - center: [0.014, -0.013, -0.014]
          radius: 0.000336
      left_jaw:
        - center: [0.005, 0.005, -0.013]
          radius: 0.000179
        - center: [0.017, 0.011, -0.013]
          radius: 0.000139
        - center: [0.004, 0.017, -0.01]
          radius: 0.000139
        - center: [-0.001, 0.001, -0.023]
          radius: 0.000129
        - center: [0.018, 0.005, -0.013]
          radius: 0.000139
        - center: [0.025, 0.012, -0.013]
          radius: 0.00012
        - center: [-0.002, -0.002, -0.007]
          radius: 0.00012
        - center: [0.011, 0.015, -0.011]
          radius: 0.000139
        - center: [0.028, 0.006, -0.013]
          radius: 0.00011
        - center: [0.007, 0.004, -0.017]
          radius: 0.000159
      right_jaw:
        - center: [0.007, 0.007, -0.013]
          radius: 0.000167
        - center: [0.02, 0.007, -0.014]
          radius: 0.000138
        - center: [0.004, 0.016, -0.01]
          radius: 0.000148
        - center: [0.001, 0.003, -0.021]
          radius: 0.000138
        - center: [-0.001, 0.001, -0.008]
          radius: 0.000128
        - center: [0.018, 0.014, -0.012]
          radius: 0.000128
        - center: [0.026, 0.011, -0.013]
          radius: 0.000119
        - center: [0.004, 0.006, -0.012]
          radius: 0.000167
        - center: [0.011, 0.006, -0.015]
          radius: 0.000157
        - center: [0.03, 0.004, -0.014]
          radius: 0.000099
    collision_sphere_buffer: 0.005
    # extra_collision_spheres:
    #   attached_object: 4
    self_collision_ignore:
      arctos_base: ["arctos_lower"]
      arctos_lower: ["arctos_middle"]
      arctos_middle: ["arctos_upper"]
      arctos_upper: ["wrist"]
      wrist: ["gripper_assembly_inner"]
      gripper_assembly_inner: ["gripper_assembly_outer"]
      gripper_assembly_outer: ["left_jaw", "right_jaw"]
      left_jaw: ["right_jaw"]
    self_collision_buffer:
      arctos_base: 0.1
      arctos_upper: 0.05
      wrist: 0.0
      gripper_assembly_inner: 0.0
      gripper_assembly_outer: 0.01
      left_jaw: 0.01
      right_jaw: 0.01
      # attached_object: 0.0
    use_global_cumul: true
    mesh_link_names:
      [
        "arctos_base",
        "arctos_lower",
        "arctos_middle",
        "arctos_upper",
        "wrist",
        "gripper_assembly_inner",
        "gripper_assembly_outer",
        "left_jaw",
        "right_jaw",
      ]
    cspace:
      joint_names:
        [
          "lower_base",
          "middle_lower",
          "upper_middle",
          "wrist_upper",
          "inner_wrist",
          "outer_inner",
          "slide_left",
          "slide_right",
        ]
      retract_config: [0.1553, -0.0454, 0.1518, 1.2497, 0.569, 1.7226, 0.0, 0.0]
      null_space_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      max_jerk: 10000.0
      max_acceleration: 10.0

    collision_link_names: null # List[str]
    collision_spheres: null #
    collision_sphere_buffer: 0.005
    extra_collision_spheres: {}
    self_collision_ignore: null # Dict[str, List[str]]
    self_collision_buffer: null # Dict[str, float]
